version: "3.9"

volumes:
  cert:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/app/data/jblue/jblue-cert"
    name: jblue-cert
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/app/data/jblue/jblue-data"
    name: jblue-data

services:
  jenkins:
    build:
      context: "/app/data/jblue"
      dockerfile: "Dockerfile"
    container_name: "jblue"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY=1 
    image: "jenkins-blueocean"
    networks: 
      - net
    ports:
      - "8070:8080/tcp"
      - "50000:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    volumes:
      - data:/var/jenkins_home
    working_dir: "/var/jenkins_home"
  docker-dind:
    container_name: "jblue-docker"
    image: "docker:dind"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks: 
      - net
    ports:
      - "2376:2376/tcp"
    privileged: true
    user: root
    volumes:
      - cert:/certs
      - data:/var/jenkins_home

networks: 
    net:
      driver: bridge
