version: "3.9"

volumes:
  cert:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${cert}"
    name: ${volume_cert}
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${data}"
    name: ${volume_data}

services:
  jenkins:
    build:
      context: "${context}"
      dockerfile: "Dockerfile"
    container_name: "${container}"
    env_file: ./.env
    image: "jenkins-blueocean"
    networks: 
      - net
    ports:
      - "${http_port}:8080/tcp"
      - "${agent_port}:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    volumes:
      - data:${JENKINS_HOME}
    working_dir: "${JENKINS_HOME}"
  docker-dind:
    container_name: "${container}-docker"
    image: "docker:dind"
    env_file: ./.env
    networks: 
      - net
    ports:
      - "${docker_port}:${docker_port}/tcp"
    privileged: true
    user: root
    volumes:
      - cert:${DOCKER_TLS_CERTDIR}
      - data:${JENKINS_HOME}

networks: 
    net:
      driver: bridge
