version: "3.9"

volumes:
  cert-ca:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/data/jenkins_cert/ca"
    name: jenkins-cert-ca
  cert-client:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/data/jenkins_cert/client"
    name: jenkins-cert-client
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/data/jenkins_home"
    name: jenkins-data

services:

  jenkins:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: "jenkins-main"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY=1 
    image: "jenkins-blueocean:2.375.2-jdk11"
    networks: 
      - net
    ports:
      - "8080:8080/tcp"
      - "50000:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    volumes:
      - cert-client:/certs/client:ro
      - data:/var/jenkins_home
    working_dir: "/var/jenkins_home"

  docker-dind:
    container_name: "jenkins-docker"
    image: "docker:dind"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks: 
      net:
        aliases: 
          - docker
    ports:
      - "2376:2376/tcp"
    privileged: true
    user: root
    volumes:
      - cert-ca:/certs/ca
      - cert-client:/certs/client
      - data:/var/jenkins_home

  docker-agent:
    build:
      context: .
      dockerfile: "jenkins-agent.Dockerfile"
    container_name: "jenkins-agent"
    image: "jenkins-agent-python"
    networks: 
      - net
    privileged: true

networks: 
    net:
      driver: bridge
